//
//  File generated by HDevelop for HALCON/DOTNET (C#) Version 11.0
//

using HalconDotNet;

public partial class HDevelopExport
{
#if !(NO_EXPORT_MAIN || NO_EXPORT_APP_MAIN)
#endif

  // Procedures 
  public void GetCalibratedImage (HObject ho_Image, out HObject ho_ImageCalibed, 
      HTuple hv_interCamera, HTuple hv_PoseNewOrigin, HTuple hv_distance)
  {



    // Local control variables 

    HTuple hv_Width = null, hv_Height = null;

    // Initialize local and output iconic variables 
    HOperatorSet.GenEmptyObj(out ho_ImageCalibed);

    HOperatorSet.GetImageSize(ho_Image, out hv_Width, out hv_Height);

    ho_ImageCalibed.Dispose();
    HOperatorSet.ImageToWorldPlane(ho_Image, out ho_ImageCalibed, hv_interCamera, 
        hv_PoseNewOrigin, hv_Width, hv_Height, hv_distance, "bilinear");



    return;
  }


}
#if !(NO_EXPORT_MAIN || NO_EXPORT_APP_MAIN)
public class HDevelopExportApp
{
  static void Main(string[] args)
  {
    new HDevelopExport();
  }
}
#endif

