/*
//
//  File generated by HDevelop for HALCON/DOTNET (C#) Version 11.0
//

using HalconDotNet;

public partial class HDevelopExport
{
#if !(NO_EXPORT_MAIN || NO_EXPORT_APP_MAIN)
#endif

  // Procedures 
  public void FindCircleCenterUseHough (HObject ho_Image, out HObject ho_HoughCenterRegion, 
      HTuple hv_CenterRow, HTuple hv_CenterColumn, HTuple hv_InnerRadius, HTuple hv_OuterRadius, 
      HTuple hv_Sigma, HTuple hv_MinGray, HTuple hv_MaxGray, HTuple hv_ExpectRadius, 
      HTuple hv_Percent, out HTuple hv_CenterRegionRow, out HTuple hv_CenterRegionColumn)
  {



    // Local iconic variables 

    HObject ho_OuterCircle, ho_InnerCircle, ho_RegionDifference;
    HObject ho_ImageReduced, ho_ImageLaplace, ho_Regions2, ho_RegionOut2;


    // Local control variables 

    HTuple hv_Area = null;

    // Initialize local and output iconic variables 
    HOperatorSet.GenEmptyObj(out ho_HoughCenterRegion);
    HOperatorSet.GenEmptyObj(out ho_OuterCircle);
    HOperatorSet.GenEmptyObj(out ho_InnerCircle);
    HOperatorSet.GenEmptyObj(out ho_RegionDifference);
    HOperatorSet.GenEmptyObj(out ho_ImageReduced);
    HOperatorSet.GenEmptyObj(out ho_ImageLaplace);
    HOperatorSet.GenEmptyObj(out ho_Regions2);
    HOperatorSet.GenEmptyObj(out ho_RegionOut2);

    ho_OuterCircle.Dispose();
    HOperatorSet.GenCircle(out ho_OuterCircle, hv_CenterRow, hv_CenterColumn, hv_OuterRadius);
    ho_InnerCircle.Dispose();
    HOperatorSet.GenCircle(out ho_InnerCircle, hv_CenterRow, hv_CenterColumn, hv_InnerRadius);

    ho_RegionDifference.Dispose();
    HOperatorSet.Difference(ho_OuterCircle, ho_InnerCircle, out ho_RegionDifference
        );

    ho_ImageReduced.Dispose();
    HOperatorSet.ReduceDomain(ho_Image, ho_RegionDifference, out ho_ImageReduced);

    ho_ImageLaplace.Dispose();
    HOperatorSet.LaplaceOfGauss(ho_ImageReduced, out ho_ImageLaplace, hv_Sigma);

    ho_Regions2.Dispose();
    HOperatorSet.Threshold(ho_ImageLaplace, out ho_Regions2, hv_MinGray, hv_MaxGray);

    ho_RegionOut2.Dispose();
    HOperatorSet.HoughCircles(ho_Regions2, out ho_RegionOut2, hv_ExpectRadius, hv_Percent, 
        0);

    HOperatorSet.AreaCenter(ho_RegionOut2, out hv_Area, out hv_CenterRegionRow, out hv_CenterRegionColumn);

    ho_OuterCircle.Dispose();
    ho_InnerCircle.Dispose();
    ho_RegionDifference.Dispose();
    ho_ImageReduced.Dispose();
    ho_ImageLaplace.Dispose();
    ho_Regions2.Dispose();
    ho_RegionOut2.Dispose();

    return;
  }


}
#if !(NO_EXPORT_MAIN || NO_EXPORT_APP_MAIN)
public class HDevelopExportApp
{
  static void Main(string[] args)
  {
    new HDevelopExport();
  }
}
#endif

*/
