//
//  File generated by HDevelop for HALCON/DOTNET (C#) Version 12.0
//

using HalconDotNet;

public partial class HDevelopExport
{
#if !(NO_EXPORT_MAIN || NO_EXPORT_APP_MAIN)
#endif

  // Procedures 
  public void FindCircleCenterUseHough (HObject ho_Image, out HObject ho_HoughCenterRegion, 
      HTuple hv_MinGray, HTuple hv_MaxGray, HTuple hv_ExpectRadius, HTuple hv_Percent, 
      out HTuple hv_CenterRegionRow, out HTuple hv_CenterRegionColumn)
  {




    // Local iconic variables 

    HObject ho_Image2;

    // Local control variables 

    HTuple hv_Area = null;
    // Initialize local and output iconic variables 
    HOperatorSet.GenEmptyObj(out ho_HoughCenterRegion);
    HOperatorSet.GenEmptyObj(out ho_Image2);
    ho_Image2.Dispose();
    HOperatorSet.Threshold(ho_Image, out ho_Image2, hv_MinGray, hv_MaxGray);

    ho_HoughCenterRegion.Dispose();
    HOperatorSet.HoughCircles(ho_Image2, out ho_HoughCenterRegion, hv_ExpectRadius, 
        hv_Percent, 0);

    HOperatorSet.AreaCenter(ho_HoughCenterRegion, out hv_Area, out hv_CenterRegionRow, 
        out hv_CenterRegionColumn);

    //gen_circle (Circle, CenterRegionRow, CenterRegionColumn, ExpectRadius)


    ho_Image2.Dispose();

    return;
  }


}
#if !(NO_EXPORT_MAIN || NO_EXPORT_APP_MAIN)
public class HDevelopExportApp
{
  static void Main(string[] args)
  {
    new HDevelopExport();
  }
}
#endif

