//
//  File generated by HDevelop for HALCON/DOTNET (C#) Version 12.0
//

using HalconDotNet;

public partial class HDevelopExport
{
#if !(NO_EXPORT_MAIN || NO_EXPORT_APP_MAIN)
  public HDevelopExport()
  {
    // Default settings used in HDevelop 
    HOperatorSet.SetSystem("width", 512);
    HOperatorSet.SetSystem("height", 512);
    if (HalconAPI.isWindows)
      HOperatorSet.SetSystem("use_window_thread","true");
    action();
  }
#endif

  // Procedures 
  // Local procedures 
  public void GetRegionOfLightOrDarkRect2 (HObject ho_Image, out HObject ho_FoundRegion, 
      HTuple hv_LightDark, HTuple hv_WidthMin, HTuple hv_WidthMax, HTuple hv_HeightMin, 
      HTuple hv_HeightMax, HTuple hv_Rect2Len1, HTuple hv_Rect2Len2)
  {




    // Local iconic variables 

    HObject ho_Region, ho_ConnectedRegions, ho_SelectedRegions;
    HObject ho_SelectedRegions1, ho_Rectangle;

    // Local control variables 

    HTuple hv_UsedThreshold = null, hv_Row = null;
    HTuple hv_Column = null, hv_Phi = null, hv_Length1 = null;
    HTuple hv_Length2 = null, hv_Row1 = null, hv_Column1 = null;
    HTuple hv_Row2 = null, hv_Column2 = null;
    // Initialize local and output iconic variables 
    HOperatorSet.GenEmptyObj(out ho_FoundRegion);
    HOperatorSet.GenEmptyObj(out ho_Region);
    HOperatorSet.GenEmptyObj(out ho_ConnectedRegions);
    HOperatorSet.GenEmptyObj(out ho_SelectedRegions);
    HOperatorSet.GenEmptyObj(out ho_SelectedRegions1);
    HOperatorSet.GenEmptyObj(out ho_Rectangle);
    ho_Region.Dispose();
    HOperatorSet.BinaryThreshold(ho_Image, out ho_Region, "max_separability", hv_LightDark, 
        out hv_UsedThreshold);

    ho_ConnectedRegions.Dispose();
    HOperatorSet.Connection(ho_Region, out ho_ConnectedRegions);
    ho_SelectedRegions.Dispose();
    HOperatorSet.SelectShape(ho_ConnectedRegions, out ho_SelectedRegions, "width", 
        "and", hv_WidthMin, hv_WidthMax);
    ho_SelectedRegions1.Dispose();
    HOperatorSet.SelectShape(ho_SelectedRegions, out ho_SelectedRegions1, "height", 
        "and", hv_HeightMin, hv_HeightMax);

    HOperatorSet.SmallestRectangle2(ho_SelectedRegions1, out hv_Row, out hv_Column, 
        out hv_Phi, out hv_Length1, out hv_Length2);
    ho_Rectangle.Dispose();
    HOperatorSet.GenRectangle2(out ho_Rectangle, hv_Row, hv_Column, hv_Phi, hv_Rect2Len1, 
        hv_Rect2Len2);
    HOperatorSet.SmallestRectangle1(ho_Rectangle, out hv_Row1, out hv_Column1, out hv_Row2, 
        out hv_Column2);
    ho_FoundRegion.Dispose();
    HOperatorSet.GenRectangle1(out ho_FoundRegion, hv_Row1, hv_Column1, hv_Row2, 
        hv_Column2);

    ho_Region.Dispose();
    ho_ConnectedRegions.Dispose();
    ho_SelectedRegions.Dispose();
    ho_SelectedRegions1.Dispose();
    ho_Rectangle.Dispose();

    return;
  }

#if !NO_EXPORT_MAIN
  // Main procedure 
  private void action()
  {


    // Local iconic variables 

    HObject ho_Image, ho_FoundRegion;
    // Initialize local and output iconic variables 
    HOperatorSet.GenEmptyObj(out ho_Image);
    HOperatorSet.GenEmptyObj(out ho_FoundRegion);
    if (HDevWindowStack.IsOpen())
    {
      HOperatorSet.SetDraw(HDevWindowStack.GetActive(), "margin");
    }

    ho_Image.Dispose();
    HOperatorSet.ReadImage(out ho_Image, "D:/WORKSPACE/hdc/Temporary/2015-01-28/test-07.tif");

    ho_FoundRegion.Dispose();
    GetRegionOfLightOrDarkRect2(ho_Image, out ho_FoundRegion, "dark", 450, 500, 150, 
        999999999, 150, 90);


    ho_Image.Dispose();
    ho_FoundRegion.Dispose();

  }

#endif


}
#if !(NO_EXPORT_MAIN || NO_EXPORT_APP_MAIN)
public class HDevelopExportApp
{
  static void Main(string[] args)
  {
    new HDevelopExport();
  }
}
#endif

