//
//  File generated by HDevelop for HALCON/DOTNET (C#) Version 12.0
//

using HalconDotNet;

public partial class HDevelopExport
{
#if !(NO_EXPORT_MAIN || NO_EXPORT_APP_MAIN)
  public HDevelopExport()
  {
    // Default settings used in HDevelop 
    HOperatorSet.SetSystem("width", 512);
    HOperatorSet.SetSystem("height", 512);
    if (HalconAPI.isWindows)
      HOperatorSet.SetSystem("use_window_thread","true");
    action();
  }
#endif

  // Procedures 
  // Local procedures 
  public void EnhanceEdgeAreaByBinaryThresholdWithMean (HObject ho_InputImage, out HObject ho_EnhancedImage, 
      out HObject ho_EnhancedRegion, HTuple hv_MeanMaskWidth, HTuple hv_MeanMaskHeight, 
      HTuple hv_EmpWidth, HTuple hv_EmpHeight, HTuple hv_EmpFactor, HTuple hv_LightDark, 
      HTuple hv_AreaMin, HTuple hv_AreaMax, HTuple hv_ClosingWidth, HTuple hv_ClosingHeight, 
      HTuple hv_DilationRadius)
  {




    // Stack for temporary objects 
    HObject[] OTemp = new HObject[20];

    // Local iconic variables 

    HObject ho_Domain, ho_ImageMean, ho_ImageEmphasize;
    HObject ho_Regions, ho_ConnectedRegions, ho_SelectedRegions;
    HObject ho_RegionFillUp, ho_RegionUnion, ho_ImageNew, ho_RegionComplement;

    // Local control variables 

    HTuple hv_Width = null, hv_Height = null, hv_UsedThreshold = null;
    // Initialize local and output iconic variables 
    HOperatorSet.GenEmptyObj(out ho_EnhancedImage);
    HOperatorSet.GenEmptyObj(out ho_EnhancedRegion);
    HOperatorSet.GenEmptyObj(out ho_Domain);
    HOperatorSet.GenEmptyObj(out ho_ImageMean);
    HOperatorSet.GenEmptyObj(out ho_ImageEmphasize);
    HOperatorSet.GenEmptyObj(out ho_Regions);
    HOperatorSet.GenEmptyObj(out ho_ConnectedRegions);
    HOperatorSet.GenEmptyObj(out ho_SelectedRegions);
    HOperatorSet.GenEmptyObj(out ho_RegionFillUp);
    HOperatorSet.GenEmptyObj(out ho_RegionUnion);
    HOperatorSet.GenEmptyObj(out ho_ImageNew);
    HOperatorSet.GenEmptyObj(out ho_RegionComplement);
    ho_Domain.Dispose();
    HOperatorSet.GetDomain(ho_InputImage, out ho_Domain);
    HOperatorSet.RegionFeatures(ho_Domain, "width", out hv_Width);
    HOperatorSet.RegionFeatures(ho_Domain, "height", out hv_Height);

    ho_ImageMean.Dispose();
    HOperatorSet.MeanImage(ho_InputImage, out ho_ImageMean, hv_MeanMaskWidth, hv_MeanMaskHeight);
    ho_ImageEmphasize.Dispose();
    HOperatorSet.Emphasize(ho_ImageMean, out ho_ImageEmphasize, hv_EmpWidth, hv_EmpHeight, 
        hv_EmpFactor);
    ho_Regions.Dispose();
    HOperatorSet.BinaryThreshold(ho_ImageEmphasize, out ho_Regions, "max_separability", 
        hv_LightDark, out hv_UsedThreshold);
    ho_ConnectedRegions.Dispose();
    HOperatorSet.Connection(ho_Regions, out ho_ConnectedRegions);
    ho_SelectedRegions.Dispose();
    HOperatorSet.SelectShape(ho_ConnectedRegions, out ho_SelectedRegions, "area", 
        "and", hv_AreaMin, hv_AreaMax);
    ho_RegionFillUp.Dispose();
    HOperatorSet.FillUp(ho_SelectedRegions, out ho_RegionFillUp);

    if ((int)((new HTuple(hv_ClosingWidth.TupleGreater(0))).TupleAnd(new HTuple(hv_ClosingHeight.TupleGreater(
        0)))) != 0)
    {
      {
      HObject ExpTmpOutVar_0;
      HOperatorSet.ClosingRectangle1(ho_RegionFillUp, out ExpTmpOutVar_0, hv_ClosingWidth, 
          hv_ClosingHeight);
      ho_RegionFillUp.Dispose();
      ho_RegionFillUp = ExpTmpOutVar_0;
      }
    }

    if ((int)(new HTuple(hv_DilationRadius.TupleGreater(0))) != 0)
    {
      {
      HObject ExpTmpOutVar_0;
      HOperatorSet.DilationCircle(ho_RegionFillUp, out ExpTmpOutVar_0, hv_DilationRadius);
      ho_RegionFillUp.Dispose();
      ho_RegionFillUp = ExpTmpOutVar_0;
      }
    }

    ho_RegionUnion.Dispose();
    HOperatorSet.Union1(ho_RegionFillUp, out ho_RegionUnion);
    ho_EnhancedRegion.Dispose();
    HOperatorSet.MoveRegion(ho_RegionUnion, out ho_EnhancedRegion, 0, 0);

    ho_ImageNew.Dispose();
    HOperatorSet.ChangeDomain(ho_InputImage, ho_Domain, out ho_ImageNew);
    ho_RegionComplement.Dispose();
    HOperatorSet.Complement(ho_RegionFillUp, out ho_RegionComplement);
    ho_EnhancedImage.Dispose();
    HOperatorSet.PaintRegion(ho_RegionFillUp, ho_ImageNew, out ho_EnhancedImage, 
        255, "fill");
    HOperatorSet.OverpaintRegion(ho_EnhancedImage, ho_RegionComplement, 0, "fill");

    ho_Domain.Dispose();
    ho_ImageMean.Dispose();
    ho_ImageEmphasize.Dispose();
    ho_Regions.Dispose();
    ho_ConnectedRegions.Dispose();
    ho_SelectedRegions.Dispose();
    ho_RegionFillUp.Dispose();
    ho_RegionUnion.Dispose();
    ho_ImageNew.Dispose();
    ho_RegionComplement.Dispose();

    return;
  }

#if !NO_EXPORT_MAIN
  // Main procedure 
  private void action()
  {


    // Local iconic variables 

    HObject ho_Image, ho_EnhancedImage, ho_FoundRegion;

    // Local control variables 

    HTuple hv_Width = null, hv_Height = null;
    // Initialize local and output iconic variables 
    HOperatorSet.GenEmptyObj(out ho_Image);
    HOperatorSet.GenEmptyObj(out ho_EnhancedImage);
    HOperatorSet.GenEmptyObj(out ho_FoundRegion);
    if (HDevWindowStack.IsOpen())
    {
      HOperatorSet.SetDraw(HDevWindowStack.GetActive(), "margin");
    }

    ho_Image.Dispose();
    HOperatorSet.ReadImage(out ho_Image, "2015-01-13_23.36.52_B_Left_Hole2b.tif");
    HOperatorSet.GetImageSize(ho_Image, out hv_Width, out hv_Height);


    ho_EnhancedImage.Dispose();ho_FoundRegion.Dispose();
    EnhanceEdgeAreaByBinaryThresholdWithMean(ho_Image, out ho_EnhancedImage, out ho_FoundRegion, 
        2, 55, 10, 10, 2, "dark", 20000, 99999999, 5, 55, 0);


    // stop(); only in hdevelop
    ho_Image.Dispose();
    ho_EnhancedImage.Dispose();
    ho_FoundRegion.Dispose();

  }

#endif


}
#if !(NO_EXPORT_MAIN || NO_EXPORT_APP_MAIN)
public class HDevelopExportApp
{
  static void Main(string[] args)
  {
    new HDevelopExport();
  }
}
#endif

